---
# tasks file for cifs-systemd-mounts
- name: Setup systemd Service for mountpoints
  template:
    src: systemd_mount.j2
    dest: "/etc/systemd/system/{{ item.dest[1:] | replace('/', '-') | trim }}.mount"
  with_items: "{{ systemd_mounts }}"
  notify: reload systemd

- name: Setup systemd Service for automount
  template:
    src: systemd_automount.j2
    dest: "/etc/systemd/system/{{ item.dest[1:] | replace('/', '-') | trim }}.automount"
  with_items: "{{ systemd_mounts }}"
  notify: reload systemd

- name: Enable mounts
  systemd:
    name: "{{ item.dest[1:] | replace('/', '-')  | trim }}.mount"
    state: stopped
    enabled: false
  with_items: "{{ systemd_mounts }}"

- name: Enable automouts
  systemd:
    name: "{{ item.dest[1:] | replace('/', '-') | trim }}.automount"
    state: started
    enabled: true
  with_items: "{{ systemd_mounts }}"
